# #################################
# #           VARIABLES           #
# #################################

restore_cache: &restore_cache
  keys:
    - v1-dependencies-{{ checksum "package.json" }}
    # fallback to using the latest cache if no exact match is found
    - v1-dependencies-

save_cache: &save_cache
  paths:
    - node_modules
  key: v1-dependencies-{{ checksum "package.json" }}

install: &install yarn install

install_aws_cli: &install_aws_cli
  - run:
        command: |
          sudo apt update   
          sudo apt -y -qq install awscli

docker: &docker
  - image: circleci/node:8-browsers

working_directory: &working-directory ~/repo

add_git_user: &add_git_user
  command: |
      git config --global user.email "marques.developpement@gmail.com"
      git config --global user.name "Marques Kevin"
      git config --global push.default simple


#################################
#      CIRCLE CI WORKFLOW       #
#################################
version: 2.1

orbs:
 percy: percy/agent@0.1.2

jobs:
  build:
    docker: *docker
    working_directory: *working-directory
    steps:
      - attach_workspace:
         at: .
      - checkout
      - restore_cache: *restore_cache
      - run: *install
      - save_cache: *save_cache
      - run: yarn test:ci
      - run: yarn build-storybook
      - run: yarn percy:publish
 
  release:
    docker: *docker
    working_directory: *working-directory
    steps:
      - checkout
      - restore_cache: *restore_cache
      - run: *install
      - save_cache: *save_cache
      - run: *add_git_user
      - run: yarn test:ci
      - run: yarn build-storybook
      - run: yarn percy:publish
      - run: *install_aws_cli
      - run: yarn deploy-storybook
      - run: yarn coveralls
      - run: yarn release

workflows:
  version: 2
  build-test-and-release:
    jobs:
      - release:
          filters:
            branches:
              only: 
                - master
      - percy/finalize_all:
         requires:
           - release
           
  build-test-and-percy:
    jobs:
      - build:
          filters:
            branches:
              ignore: 
                - master
                - dev
      - percy/finalize_all:
         requires:
           - build
